import { Component, For, createSignal, createMemo } from "solid-js";
import TitleComponent from "../components/Title";
import { Events, GetDay, type Event } from "../assets/db/Events";

interface EventDay {
  lowestUnixTime: null | number;
  highestUnixTime: null | number;
  events: any;
}

const hourSize = 200;

let formatedEvents: Record<string, EventDay> = {};

const Event: Component = () => {
  const [currentDay, setDay] = createSignal<number>(0);

  const initDates = () => {
    // Gets the lowest and highest unix out of Events, and also organizes them by day
    Events.forEach((event: Event) => {
      const unixBeginTime = event.beginDate.getTime();
      const unixEndTime = event.endDate.getTime();

      // Creates eventDay
      const day = event.beginDate.getDay();
      if (!formatedEvents[day]) {
        formatedEvents[day] = {
          lowestUnixTime: null,
          highestUnixTime: null,
          events: {},
        } as EventDay;
      }

      // Creates location if it doesn't exist
      const eventDay = formatedEvents[day];
      const location = event.location;
      if (!eventDay.events[location]) {
        eventDay.events[location] = [];
      }

      if (
        eventDay.lowestUnixTime == null ||
        unixBeginTime < eventDay.lowestUnixTime
      ) {
        eventDay.lowestUnixTime = unixBeginTime;
      }

      if (
        eventDay.highestUnixTime == null ||
        unixEndTime > eventDay.highestUnixTime
      ) {
        eventDay.highestUnixTime = unixEndTime;
      }

      eventDay.events[location].push(event);
    });
  };

  initDates();

  const formatTime = (date: Date) => {
    // Generated by claude
    return `${date.getHours()}:${date
      .getMinutes()
      .toString()
      .padStart(2, "0")}`;
  };

  const getEventPosition = (event: Event, eventDay) => {
    // Use eventday here
    if (!startingDate) return { left: 0, width: hourSize };

    const eventStartDate = event.beginDate;
    const eventEndDate = event.endDate;

    // I hate math - Jos
    const unixDiff = eventStartDate.getTime() - startingDate.getTime();
    const hoursDiff = unixDiff / (1000 * 60 * 60);

    const eventUnixDuration = eventEndDate.getTime() - eventStartDate.getTime();
    const hoursDuration = eventUnixDuration / (1000 * 60 * 60);

    return {
      left: hoursDiff * hourSize,
      width: hoursDuration * hourSize,
    };
  };

  const getTimeline = createMemo(() => {
    const eventDay = formatedEvents[currentDay()] as EventDay;
    if (!eventDay) {
      return [];
    }

    const timeline: Array<Date> = [];
    const start = new Date(eventDay.lowestUnixTime!);
    const end = new Date(eventDay.highestUnixTime!);

    for (let num = 0; num < end.getHours() + 1 - start.getHours(); num++) {
      const date = new Date(start);
      date.setHours(start.getHours() + num);
      timeline.push(date);
    }

    return timeline;
  });

  const getDays = createMemo(() => {
    return Object.keys(formatedEvents)
      .map((day) => parseInt(day))
      .sort((a, b) => a - b);
  });

  const getEvents = createMemo(() => {
    return formatedEvents[currentDay()] || {};
  });

  return (
    <div class="w-full h-full flex flex-col gap-4 pt-4">
      <nav class="w-full h-fit px-4 space-y-4">
        <TitleComponent children="Events" />

        <div class="w-full h-fit flex justify-between gap-2 overflow-x-auto">
          <For each={getDays()}>
            {(dayNumber) => (
              <button
                class={`p-2 w-full min-w-fit rounded-3xl transition-colors ${
                  currentDay() === dayNumber
                    ? "bg-accent text-white"
                    : "bg-primary-container-bg dark:bg-primary-container-bg-dark border border-primary-border dark:border-primary-border-dark text-primary-text dark:text-primary-text-dark hover:bg-accent hover:text-white"
                }`}
                onClick={() => setDay(dayNumber)}
              >
                {GetDay(dayNumber)}
              </button>
            )}
          </For>
        </div>
      </nav>

      <div class="w-full h-full flex flex-col px-4">
        <section class="w-full h-full overflow-auto hide-scroll rounded-4xl">
          <div class="flex flex-col min-w-fit">
            <section class="flex">
              <div class="w-32 h-fill bg-accent text-white flex items-center justify-center">
                <p class="font-medium text-sm">Location</p>
              </div>
              <For each={getTimeline()}>
                {(timeSlot) => (
                  <div
                    class="bg-accent text-white flex items-center justify-start p-4"
                    style={`width: ${hourSize}px; height: 60px`}
                  >
                    <p class="font-medium">{formatTime(timeSlot)}</p>
                  </div>
                )}
              </For>
            </section>

            <section class="flex flex-col">
              <div
                class="relative border-b border-primary-border dark:border-primary-border-dark h-24 flex"
                style={`width: ${32 * 4 + getTimeline().length * hourSize}px`}
              >
                <For each={getEvents().events[location]}>
                  {(event) => {
                    <div class="w-32 h-full flex justify-between items-center p-4 text-primary-text dark:text-primary-text-dark">
                      <p class="text-md font-medium">{location}</p>
                    </div>;
                    {
                      /* <div class="relative flex-1">
                      
                          const position = getEventPosition(event);
                          return (
                            <div
                              class="absolute top-2 bottom-2 bg-primary-container-bg dark:bg-primary-container-bg-dark rounded-2xl p-4 flex flex-col justify-center border border-primary-border dark:border-primary-border-dark"
                              style={`left: ${position.left}px; width: ${position.width}px`}
                            >
                              <p class="text-primary-text dark:text-primary-text-dark text-sm font-medium truncate">
                                {event.title}
                              </p>

                              <p class="text-secondary-text dark:text-secondary-text-dark text-xs truncate">
                                {formatTime(event.beginDate)} -{" "}
                                {formatTime(event.endDate)}
                              </p>
                            </div>
                          );
                       
                    </div> */
                    }
                  }}
                </For>
              </div>
            </section>
          </div>
        </section>
      </div>
    </div>
  );
};

export default Event;
